# NOVAGUARD-AI/action.yml
name: 'NovaGuard AI Code Review'
description: 'An intelligent code review co-pilot using LLMs and traditional tools via local Ollama.'
author: 'Your Name/Organization Here' # Thay thế nếu muốn
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for GitHub API interactions (e.g., fetching PR data if needed, though SARIF upload is preferred via a separate action).'
    required: true
    default: '${{ github.token }}'
  ollama_base_url:
    description: 'Base URL of the running Ollama server.'
    required: true
    default: 'http://localhost:11434' # Mặc định cho self-hosted runner
  project_config_path:
    description: 'Optional path to a project-specific NovaGuard AI config directory within the target repository (e.g., .github/novaguard_config/).'
    required: false
  sarif_output_file:
    description: 'Filename for the generated SARIF report within GITHUB_WORKSPACE.'
    required: false
    default: 'novaguard-report.sarif'
  fail_on_severity:
    description: 'Minimum severity (e.g., error, warning, note) to cause the action to fail. Default is "none". Allowed: error, warning, note, none.'
    required: false
    default: 'none'

outputs:
  report_summary_text:
    description: 'A brief text summary of review findings.'
  sarif_file_path:
    description: 'Workspace-relative path to the generated SARIF report file.'

runs:
  using: 'docker'
  image: 'Dockerfile'