# NOVAGUARD-AI/config/models.yml

# Chế độ hoạt động mặc định nếu không có gì ghi đè (ví dụ: "production" hoặc "test")
# Giá trị này có thể được ghi đè bởi biến môi trường NOVAGUARD_ACTIVE_MODE
default_active_mode: "production"

modes:
  production:
    # Model cho môi trường production - ưu tiên độ chính xác cao
    agents:
      StyleGuardian: "codellama:13b-instruct-q5_K_M"
      BugHunter: "deepseek-coder:33b-instruct-q4_K_M"
      SecuriSense: "codellama:34b-instruct-q5_K_M" # Có thể dùng model lớn hơn cho security
      OptiTune: "codellama:13b-instruct-q5_K_M"
      MetaReviewer: "mistral:7b-instruct-v0.2-q5_K_M" # Hoặc một model lớn hơn như Mixtral nếu cần context dài
    # tasks: # (Tùy chọn)
      # summarize_findings_long: "mixtral:8x7b-instruct-v0.1-q4_K_M"

  test:
    # Model cho môi trường test - ưu tiên tốc độ, không cần quá chính xác
    # Đảm bảo các model này đã được pull về Ollama server của bạn.
    # Ví dụ các model nhỏ, nhanh (tên model có thể thay đổi tùy theo Ollama và các model bạn có):
    agents:
      StyleGuardian: "tinydolphin:1.1b-v2.8-q4_K_M" # Hoặc "phi:2.7b-chat-v2-q4_K_M" nếu bạn đã pull phi-2
      BugHunter: "phi:2.7b-chat-v2-q4_K_M" # Phi-2 khá tốt cho code tasks nhỏ
      SecuriSense: "tinydolphin:1.1b-v2.8-q4_K_M"
      OptiTune: "tinydolphin:1.1b-v2.8-q4_K_M"
      MetaReviewer: "orca-mini:3b-v3-q4_K_M" # Hoặc một model nhỏ khác
    # tasks:
      # summarize_findings_long: "orca-mini:3b-v3-q4_K_M"

# (Tùy chọn) Các model được chia sẻ hoặc fallback nếu không tìm thấy trong mode cụ thể
# shared_models:
#   fallback_general_agent: "ollama-is-cool:latest" # Ví dụ